[package]
name = "passthru"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.6", features = ["derive"] }
fuse-sys = { git = "https://github.com/euugenechou/fuse-sys.git", features = ["auto"] }
libc = "0.2.148"
xmp = { path = "xmp" }
